[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python start_production.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.envs]
NODE_ENV = "production"
